import { sql } from "drizzle-orm";
import { sqliteTable } from "drizzle-orm/sqlite-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";

export const TOSS_NAMES = [
  "Miss",
  "M1",
  "M2",
  "M3",
  "M4",
  "M5",
  "M6",
  "M7",
  "M8",
  "M9",
  "M10",
  "M11",
  "M12",
  "M13",
  "M14",
  "M15",
  "M16",
  "M17",
  "M18",
  "M19",
  "M20",
  "S1",
  "S2",
  "S3",
  "S4",
  "S5",
  "S6",
  "S7",
  "S8",
  "S9",
  "S10",
  "S11",
  "S12",
  "S13",
  "S14",
  "S15",
  "S16",
  "S17",
  "S18",
  "S19",
  "S20",
  "D1",
  "D2",
  "D3",
  "D4",
  "D5",
  "D6",
  "D7",
  "D8",
  "D9",
  "D10",
  "D11",
  "D12",
  "D13",
  "D14",
  "D15",
  "D16",
  "D17",
  "D18",
  "D19",
  "D20",
  "T1",
  "T2",
  "T3",
  "T4",
  "T5",
  "T6",
  "T7",
  "T8",
  "T9",
  "T10",
  "T11",
  "T12",
  "T13",
  "T14",
  "T15",
  "T16",
  "T17",
  "T18",
  "T19",
  "T20",
  "25",
  "Bull",
] as const;
export const TOSS_SEGMENTS = [
  "Outside",
  "SingleInner",
  "SingleOuter",
  "Single",
  "Double",
  "Triple",
] as const;

export const tossTable = sqliteTable("tosses", (t) => ({
  id: t.integer("id").primaryKey({ autoIncrement: true }),
  name: t.text({
    enum: TOSS_NAMES,
  }).notNull(),
  segment: t.text({
    enum: TOSS_SEGMENTS,
  }).notNull(),
  value: t.integer().notNull(),
  multiplier: t.integer().notNull(),
  coords_x: t.real(),
  coords_y: t.real(),
  updated_at: t.integer({ mode: "timestamp_ms" }).$onUpdate(() =>
    sql`(CURRENT_TIMESTAMP)`
  ).notNull(),
  created_at: t.integer({ mode: "timestamp_ms" }).default(
    sql`(CURRENT_TIMESTAMP)`,
  ).notNull(),
  deleted_at: t.integer({ mode: "timestamp_ms" }),
}));

export const tossInsertSchema = createInsertSchema(tossTable);
export const tossSelectSchema = createSelectSchema(tossTable);
