import z from "zod";

export const TOSS_NAMES = [
  "Miss",
  "M1",
  "M2",
  "M3",
  "M4",
  "M5",
  "M6",
  "M7",
  "M8",
  "M9",
  "M10",
  "M11",
  "M12",
  "M13",
  "M14",
  "M15",
  "M16",
  "M17",
  "M18",
  "M19",
  "M20",
  "S1",
  "S2",
  "S3",
  "S4",
  "S5",
  "S6",
  "S7",
  "S8",
  "S9",
  "S10",
  "S11",
  "S12",
  "S13",
  "S14",
  "S15",
  "S16",
  "S17",
  "S18",
  "S19",
  "S20",
  "D1",
  "D2",
  "D3",
  "D4",
  "D5",
  "D6",
  "D7",
  "D8",
  "D9",
  "D10",
  "D11",
  "D12",
  "D13",
  "D14",
  "D15",
  "D16",
  "D17",
  "D18",
  "D19",
  "D20",
  "T1",
  "T2",
  "T3",
  "T4",
  "T5",
  "T6",
  "T7",
  "T8",
  "T9",
  "T10",
  "T11",
  "T12",
  "T13",
  "T14",
  "T15",
  "T16",
  "T17",
  "T18",
  "T19",
  "T20",
  "25",
  "Bull",
] as const;
export const TOSS_SEGMENTS = [
  "Outside",
  "SingleInner",
  "SingleOuter",
  "Single",
  "Double",
  "Triple",
] as const;

export const tossSchema = z.object({
  id: z.number().int(),
  name: z.enum(TOSS_NAMES),
  segment: z.enum(TOSS_SEGMENTS),
  value: z.number().int(),
  multiplier: z.number().int(),
  coords: z.object({
    x: z.number().nullable(),
    y: z.number().nullable(),
  }),
  meta: z.object({
    updated_at: z.number().int(),
    created_at: z.number().int(),
    deleted_at: z.number().int().optional(),
  }),
});
export type Toss = z.infer<typeof tossSchema>;

export const tossCreateSchema = tossSchema.omit({
  id: true,
  meta: true,
});

export const tossReadSchema = z.object({
  id: z.coerce.number().int().min(1),
});

export const TOSS_LIST_LIMIT_DEFAULT = 100 as const;
export const TOSS_LIST_OFFSET_DEFAULT = 0 as const;
export const tossListSchema = z.object({
  limit: z.number().int().min(1).default(TOSS_LIST_LIMIT_DEFAULT),
  offset: z.number().int().min(0).default(TOSS_LIST_OFFSET_DEFAULT),
}).default({
  limit: TOSS_LIST_LIMIT_DEFAULT,
  offset: TOSS_LIST_OFFSET_DEFAULT,
});
